#:kivy 2.1.0

#:import NoTransition kivy.uix.screenmanager.NoTransition
#:include screen_splash.kv
#:include screen_home.kv

# ScreenManager:
<RootScreen>:
    id: screen_manager
    transition: NoTransition()

    ScreenSplash:
        id: screen_splash
        name: 'screen_splash'
        screen_manager: screen_manager

    ScreenHome:
        id: screen_home
        name: 'screen_home'
        screen_manager: screen_manager
